version: 2

project_name: cert2jks

before:
  hooks:
    - go mod tidy

builds:
  - id: cert2jks
    main: ./main.go
    binary: cert2jks
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: cert2jks
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE*
      - resources/**/*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.REPO_OWNER }}/cert2jks:{{ .Version }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.REPO_OWNER }}/cert2jks"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - image_templates:
      - "ghcr.io/{{ .Env.REPO_OWNER }}/cert2jks:{{ .Version }}-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.REPO_OWNER }}/cert2jks"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

docker_manifests:
  - name_template: "ghcr.io/{{ .Env.REPO_OWNER }}/cert2jks:{{ .Version }}"
    image_templates:
      - "ghcr.io/{{ .Env.REPO_OWNER }}/cert2jks:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.REPO_OWNER }}/cert2jks:{{ .Version }}-arm64"
  - name_template: "ghcr.io/{{ .Env.REPO_OWNER }}/cert2jks:latest"
    image_templates:
      - "ghcr.io/{{ .Env.REPO_OWNER }}/cert2jks:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.REPO_OWNER }}/cert2jks:{{ .Version }}-arm64"

release:
  github:
    owner: digitalis-io
    name: cert2jks
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## cert2jks {{ .Tag }}
  footer: |
    **Full Changelog**: https://github.com/digitalis-io/cert2jks/compare/{{ .PreviousTag }}...{{ .Tag }}
